### ISSUE TITLE
Can not generate API

### ISSUE THREAD

**Issue by ohid** [whois-server-list/domain-api-php#1]
I have signup on there website http://whois-api.domaininformation.de/
But I can  not generate my API key or may be I didn't find where to generate it.

Can you please help me to generate my API key like give me a screenshot of that page?

Thanks

**Comment by ohid** [comment]
Now I am getting this error when submitting a request 

WhoisApiException in WhoisApi.php line 162:
Transport failed.

**Comment by malkusch** [comment]
Getting an API key is documented [here](http://docs.mashape.com/api-keys#changing).

> WhoisApiException in WhoisApi.php line 162:
> Transport failed.

Sounds like a network issue. Could you execute this curl command with your key and see if you have connectivity?

```
curl 'https://whois-v0.p.mashape.com/domains' -H 'X-Mashape-Key: $API_KEY'
```
